- name: Conda Bot
  email: 18747875+conda-bot@users.noreply.github.com
  github: conda-bot
- name: Dan Yeaw
  email: dan@yeaw.me
  github: danyeaw
- name: Ken Odegard
  email: kodegard@anaconda.com
  github: kenodegard
