name: Prepare authors

on:
  workflow_dispatch:
    inputs:
      since:
        description: Commit range to scan
        required: true
        default: tag
        type: choice
        options: [tag, all]

permissions:
  contents: read

jobs:
  prepare:
    if: '!github.event.repository.fork'
    runs-on: ubuntu-latest
    steps:
      - uses: conda/actions/prepare-authors@faab6a942e6e8490cd82eee2f6a2b174dace8e9e # v26.9.1
        with:
          since: ${{ inputs.since }}
          base-branch: main
          token: ${{ secrets.SYNC_TOKEN }}
